/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.Usuario;
import java.util.ArrayList;
import negocio.Funcionalidad;

/**
 *
 * @author becal
 */
public class Vista extends javax.swing.JFrame {

    ArrayList<Usuario> lista = new ArrayList();
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Principal = new javax.swing.JPanel();
        jPanel_Superior = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jPanel_LateralIzq = new javax.swing.JPanel();
        jPanel_Central = new javax.swing.JPanel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Celular = new javax.swing.JLabel();
        jTextField_Celular = new javax.swing.JTextField();
        jPanel_LateralDer = new javax.swing.JPanel();
        jPanel_Inferior = new javax.swing.JPanel();
        jButton_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Principal.setLayout(new java.awt.BorderLayout());

        jPanel_Superior.setBackground(new java.awt.Color(135, 113, 113));
        jPanel_Superior.setPreferredSize(new java.awt.Dimension(411, 50));

        jLabel_Titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_Titulo.setText("Captura Datos");

        javax.swing.GroupLayout jPanel_SuperiorLayout = new javax.swing.GroupLayout(jPanel_Superior);
        jPanel_Superior.setLayout(jPanel_SuperiorLayout);
        jPanel_SuperiorLayout.setHorizontalGroup(
            jPanel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(jPanel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_SuperiorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_Titulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_SuperiorLayout.setVerticalGroup(
            jPanel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_SuperiorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_Titulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel_Principal.add(jPanel_Superior, java.awt.BorderLayout.PAGE_START);

        jPanel_LateralIzq.setBackground(new java.awt.Color(214, 182, 182));
        jPanel_LateralIzq.setPreferredSize(new java.awt.Dimension(50, 143));

        javax.swing.GroupLayout jPanel_LateralIzqLayout = new javax.swing.GroupLayout(jPanel_LateralIzq);
        jPanel_LateralIzq.setLayout(jPanel_LateralIzqLayout);
        jPanel_LateralIzqLayout.setHorizontalGroup(
            jPanel_LateralIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel_LateralIzqLayout.setVerticalGroup(
            jPanel_LateralIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        jPanel_Principal.add(jPanel_LateralIzq, java.awt.BorderLayout.LINE_START);

        jPanel_Central.setBackground(new java.awt.Color(214, 183, 183));

        jTextField_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_Nombre.setText("Nombre");

        jLabel_Celular.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_Celular.setText("Celular");

        jTextField_Celular.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel_CentralLayout = new javax.swing.GroupLayout(jPanel_Central);
        jPanel_Central.setLayout(jPanel_CentralLayout);
        jPanel_CentralLayout.setHorizontalGroup(
            jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CentralLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CentralLayout.createSequentialGroup()
                        .addComponent(jLabel_Celular)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jTextField_Celular)))
                    .addComponent(jLabel_Nombre))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel_CentralLayout.setVerticalGroup(
            jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Celular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Celular))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel_Principal.add(jPanel_Central, java.awt.BorderLayout.CENTER);

        jPanel_LateralDer.setBackground(new java.awt.Color(214, 182, 182));
        jPanel_LateralDer.setPreferredSize(new java.awt.Dimension(50, 143));

        javax.swing.GroupLayout jPanel_LateralDerLayout = new javax.swing.GroupLayout(jPanel_LateralDer);
        jPanel_LateralDer.setLayout(jPanel_LateralDerLayout);
        jPanel_LateralDerLayout.setHorizontalGroup(
            jPanel_LateralDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel_LateralDerLayout.setVerticalGroup(
            jPanel_LateralDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        jPanel_Principal.add(jPanel_LateralDer, java.awt.BorderLayout.LINE_END);

        jPanel_Inferior.setBackground(new java.awt.Color(214, 182, 182));

        jButton_Guardar.setBackground(new java.awt.Color(226, 206, 206));
        jButton_Guardar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_Guardar.setText("Guardar");
        jButton_Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Guardar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InferiorLayout = new javax.swing.GroupLayout(jPanel_Inferior);
        jPanel_Inferior.setLayout(jPanel_InferiorLayout);
        jPanel_InferiorLayout.setHorizontalGroup(
            jPanel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Guardar)
                .addGap(110, 110, 110))
        );
        jPanel_InferiorLayout.setVerticalGroup(
            jPanel_InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InferiorLayout.createSequentialGroup()
                .addComponent(jButton_Guardar)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        jPanel_Principal.add(jPanel_Inferior, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel_Principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        String nombre,celular;
        nombre=this.jTextField_Nombre.getText();
        celular=this.jTextField_Celular.getText();
        
        Usuario usuario=new Usuario(nombre,celular);
        this.lista.add(usuario);
        Funcionalidad.main(lista);
        this.jTextField_Nombre.setText("");
        this.jTextField_Celular.setText("");
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JLabel jLabel_Celular;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JPanel jPanel_Central;
    private javax.swing.JPanel jPanel_Inferior;
    private javax.swing.JPanel jPanel_LateralDer;
    private javax.swing.JPanel jPanel_LateralIzq;
    private javax.swing.JPanel jPanel_Principal;
    private javax.swing.JPanel jPanel_Superior;
    private javax.swing.JTextField jTextField_Celular;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
